import { DEFAULT_TELEGRAM_CHUNK_SIZE_BYTES } from "../database";

export const TELEGRAM_CHUNK_SIZE_BYTES = DEFAULT_TELEGRAM_CHUNK_SIZE_BYTES;
export const MAX_TELEGRAM_MULTIPART_BYTES = 20 * 1024 * 1024 * 1024;
export const MAX_TELEGRAM_MULTIPART_CHUNKS = Math.ceil(MAX_TELEGRAM_MULTIPART_BYTES / TELEGRAM_CHUNK_SIZE_BYTES);
export const DIRECT_MULTIPART_ACCESS_MAX_CHUNKS = MAX_TELEGRAM_MULTIPART_CHUNKS;
export const DIRECT_MULTIPART_ACCESS_MAX_BYTES = MAX_TELEGRAM_MULTIPART_BYTES;

export function maxTelegramMultipartChunks(chunkSizeBytes: number): number {
  return Math.ceil(MAX_TELEGRAM_MULTIPART_BYTES / chunkSizeBytes);
}
